# 项目相关配置
zhiqi:
  name: ZhiQi
  version: 0.0.1
  copyrightYear: 2023
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/MyGithub/zhiqi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  captchaType: math


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9495
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  shutdown: graceful

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zhiqi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

spring:
  profiles:
    active: druid
  servlet:
    # 文件上传
    multipart:
      # 单个文件大小
      max-request-size: 10MB
      # 设置总上传的文件大小
      max-file-size: 20MB
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages


# 日志配置
logging:
  level:
    com.zhiqi: debug
    org.springframework: warn

# 文档配置
swagger:
  # 是否开启swagger文档
  enabled: true
  # 访问路径
  pathMapping: /dev-api

jwt:
  headerTokenName: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  # minutes
  expiration: 30

